{
  status: 200,
  order: {
    _id: '629963cc6ed630fab6d27d5e',
    client: '556592540965@s.whatsapp.net',
    subject: 'Temporário',
    description: 'Apenas um teste',
    category: '979884444460675100',
    finished: false,
    channel: '979862673401471068',
    __v: 0
  }
}
LimitedCollection(26) [Map] {
  '979862662320128041' => <ref *1> CategoryChannel {
    type: 'GUILD_CATEGORY',
    guild: Guild {
      id: '978660471286665256',
      name: 'Hifuzion',
      icon: '7e6391e8eb99e881b2821d011523ee54',
      features: [],
      commands: [GuildApplicationCommandManager],
      members: [GuildMemberManager],
      channels: [GuildChannelManager],
      bans: [GuildBanManager],
      roles: [RoleManager],
      presences: PresenceManager {},
      voiceStates: [VoiceStateManager],
      stageInstances: [StageInstanceManager],
      invites: [GuildInviteManager],
      scheduledEvents: [GuildScheduledEventManager],
      available: true,
      shardId: 0,
      splash: null,
      banner: null,
      description: null,
      verificationLevel: 'NONE',
      vanityURLCode: null,
      nsfwLevel: 'DEFAULT',
      premiumSubscriptionCount: 0,
      discoverySplash: null,
      memberCount: 9,
      large: false,
      premiumProgressBarEnabled: false,
      applicationId: null,
      afkTimeout: 300,
      afkChannelId: null,
      systemChannelId: null,
      premiumTier: 'NONE',
      explicitContentFilter: 'DISABLED',
      mfaLevel: 'NONE',
      joinedTimestamp: 1653690625094,
      defaultMessageNotifications: 'ALL_MESSAGES',
      systemChannelFlags: [SystemChannelFlags],
      maximumMembers: 500000,
      maximumPresences: null,
      approximateMemberCount: null,
      approximatePresenceCount: null,
      vanityURLUses: null,
      rulesChannelId: null,
      publicUpdatesChannelId: null,
      preferredLocale: 'en-US',
      ownerId: '342390906097500160',
      emojis: [GuildEmojiManager],
      stickers: [GuildStickerManager]
    },
    guildId: '978660471286665256',
    parentId: null,
    permissionOverwrites: PermissionOverwriteManager { channel: [Circular *1] },
    id: '979862662320128041',
    name: '—————Manager—————',
    rawPosition: 0
  },
  '979862663565828106' => <ref *2> CategoryChannel {
    type: 'GUILD_CATEGORY',
    guild: Guild {
      id: '978660471286665256',
      name: 'Hifuzion',
      icon: '7e6391e8eb99e881b2821d011523ee54',
      features: [],
      commands: [GuildApplicationCommandManager],
      members: [GuildMemberManager],
      channels: [GuildChannelManager],
      bans: [GuildBanManager],
      roles: [RoleManager],
      presences: PresenceManager {},
      voiceStates: [VoiceStateManager],
      stageInstances: [StageInstanceManager],
      invites: [GuildInviteManager],
      scheduledEvents: [GuildScheduledEventManager],
      available: true,
      shardId: 0,
      splash: null,
      banner: null,
      description: null,
      verificationLevel: 'NONE',
      vanityURLCode: null,
      nsfwLevel: 'DEFAULT',
      premiumSubscriptionCount: 0,
      discoverySplash: null,
      memberCount: 9,
      large: false,
      premiumProgressBarEnabled: false,
      applicationId: null,
      afkTimeout: 300,
      afkChannelId: null,
      systemChannelId: null,
      premiumTier: 'NONE',
      explicitContentFilter: 'DISABLED',
      mfaLevel: 'NONE',
      joinedTimestamp: 1653690625094,
      defaultMessageNotifications: 'ALL_MESSAGES',
      systemChannelFlags: [SystemChannelFlags],
      maximumMembers: 500000,
      maximumPresences: null,
      approximateMemberCount: null,
      approximatePresenceCount: null,
      vanityURLUses: null,
      rulesChannelId: null,
      publicUpdatesChannelId: null,
      preferredLocale: 'en-US',
      ownerId: '342390906097500160',
      emojis: [GuildEmojiManager],
      stickers: [GuildStickerManager]
    },
    guildId: '978660471286665256',
    parentId: null,
    permissionOverwrites: PermissionOverwriteManager { channel: [Circular *2] },
    id: '979862663565828106',
    name: '—————warnings—————',
    rawPosition: 1
  },
  '979862664585027584' => <ref *3> CategoryChannel {
    type: 'GUILD_CATEGORY',
    guild: Guild {
      id: '978660471286665256',
      name: 'Hifuzion',
      icon: '7e6391e8eb99e881b2821d011523ee54',
      features: [],
      commands: [GuildApplicationCommandManager],
      members: [GuildMemberManager],
      channels: [GuildChannelManager],
      bans: [GuildBanManager],
      roles: [RoleManager],
      presences: PresenceManager {},
      voiceStates: [VoiceStateManager],
      stageInstances: [StageInstanceManager],
      invites: [GuildInviteManager],
      scheduledEvents: [GuildScheduledEventManager],
      available: true,
      shardId: 0,
      splash: null,
      banner: null,
      description: null,
      verificationLevel: 'NONE',
      vanityURLCode: null,
      nsfwLevel: 'DEFAULT',
      premiumSubscriptionCount: 0,
      discoverySplash: null,
      memberCount: 9,
      large: false,
      premiumProgressBarEnabled: false,
      applicationId: null,
      afkTimeout: 300,
      afkChannelId: null,
      systemChannelId: null,
      premiumTier: 'NONE',
      explicitContentFilter: 'DISABLED',
      mfaLevel: 'NONE',
      joinedTimestamp: 1653690625094,
      defaultMessageNotifications: 'ALL_MESSAGES',
      systemChannelFlags: [SystemChannelFlags],
      maximumMembers: 500000,
      maximumPresences: null,
      approximateMemberCount: null,
      approximatePresenceCount: null,
      vanityURLUses: null,
      rulesChannelId: null,
      publicUpdatesChannelId: null,
      preferredLocale: 'en-US',
      ownerId: '342390906097500160',
      emojis: [GuildEmojiManager],
      stickers: [GuildStickerManager]
    },
    guildId: '978660471286665256',
    parentId: null,
    permissionOverwrites: PermissionOverwriteManager { channel: [Circular *3] },
    id: '979862664585027584',
    name: '</chats text>',
    rawPosition: 3
  },
  '979862668301201418' => <ref *4> CategoryChannel {
    type: 'GUILD_CATEGORY',
    guild: Guild {
      id: '978660471286665256',
      name: 'Hifuzion',
      icon: '7e6391e8eb99e881b2821d011523ee54',
      features: [],
      commands: [GuildApplicationCommandManager],
      members: [GuildMemberManager],
      channels: [GuildChannelManager],
      bans: [GuildBanManager],
      roles: [RoleManager],
      presences: PresenceManager {},
      voiceStates: [VoiceStateManager],
      stageInstances: [StageInstanceManager],
      invites: [GuildInviteManager],
      scheduledEvents: [GuildScheduledEventManager],
      available: true,
      shardId: 0,
      splash: null,
      banner: null,
      description: null,
      verificationLevel: 'NONE',
      vanityURLCode: null,
      nsfwLevel: 'DEFAULT',
      premiumSubscriptionCount: 0,
      discoverySplash: null,
      memberCount: 9,
      large: false,
      premiumProgressBarEnabled: false,
      applicationId: null,
      afkTimeout: 300,
      afkChannelId: null,
      systemChannelId: null,
      premiumTier: 'NONE',
      explicitContentFilter: 'DISABLED',
      mfaLevel: 'NONE',
      joinedTimestamp: 1653690625094,
      defaultMessageNotifications: 'ALL_MESSAGES',
      systemChannelFlags: [SystemChannelFlags],
      maximumMembers: 500000,
      maximumPresences: null,
      approximateMemberCount: null,
      approximatePresenceCount: null,
      vanityURLUses: null,
      rulesChannelId: null,
      publicUpdatesChannelId: null,
      preferredLocale: 'en-US',
      ownerId: '342390906097500160',
      emojis: [GuildEmojiManager],
      stickers: [GuildStickerManager]
    },
    guildId: '978660471286665256',
    parentId: null,
    permissionOverwrites: PermissionOverwriteManager { channel: [Circular *4] },
    id: '979862668301201418',
    name: '</programação>',
    rawPosition: 5
  },
  '979862673401471068' => <ref *5> TextChannel {
    type: 'GUILD_TEXT',
    guild: Guild {
      id: '978660471286665256',
      name: 'Hifuzion',
      icon: '7e6391e8eb99e881b2821d011523ee54',
      features: [],
      commands: [GuildApplicationCommandManager],
      members: [GuildMemberManager],
      channels: [GuildChannelManager],
      bans: [GuildBanManager],
      roles: [RoleManager],
      presences: PresenceManager {},
      voiceStates: [VoiceStateManager],
      stageInstances: [StageInstanceManager],
      invites: [GuildInviteManager],
      scheduledEvents: [GuildScheduledEventManager],
      available: true,
      shardId: 0,
      splash: null,
      banner: null,
      description: null,
      verificationLevel: 'NONE',
      vanityURLCode: null,
      nsfwLevel: 'DEFAULT',
      premiumSubscriptionCount: 0,
      discoverySplash: null,
      memberCount: 9,
      large: false,
      premiumProgressBarEnabled: false,
      applicationId: null,
      afkTimeout: 300,
      afkChannelId: null,
      systemChannelId: null,
      premiumTier: 'NONE',
      explicitContentFilter: 'DISABLED',
      mfaLevel: 'NONE',
      joinedTimestamp: 1653690625094,
      defaultMessageNotifications: 'ALL_MESSAGES',
      systemChannelFlags: [SystemChannelFlags],
      maximumMembers: 500000,
      maximumPresences: null,
      approximateMemberCount: null,
      approximatePresenceCount: null,
      vanityURLUses: null,
      rulesChannelId: null,
      publicUpdatesChannelId: null,
      preferredLocale: 'en-US',
      ownerId: '342390906097500160',
      emojis: [GuildEmojiManager],
      stickers: [GuildStickerManager]
    },
    guildId: '978660471286665256',
    parentId: '979862662320128041',
    permissionOverwrites: PermissionOverwriteManager { channel: [Circular *5] },
    messages: MessageManager { channel: [Circular *5] },
    threads: ThreadManager { channel: [Circular *5] },
    nsfw: false,
    id: '979862673401471068',
    name: '《💻》testes',
    rawPosition: 0,
    topic: null,
    lastMessageId: '982052760734298162',
    rateLimitPerUser: 0
  },
  '979862674462621776' => <ref *6> VoiceChannel {
    type: 'GUILD_VOICE',
    guild: Guild {
      id: '978660471286665256',
      name: 'Hifuzion',
      icon: '7e6391e8eb99e881b2821d011523ee54',
      features: [],
      commands: [GuildApplicationCommandManager],
      members: [GuildMemberManager],
      channels: [GuildChannelManager],
      bans: [GuildBanManager],
      roles: [RoleManager],
      presences: PresenceManager {},
      voiceStates: [VoiceStateManager],
      stageInstances: [StageInstanceManager],
      invites: [GuildInviteManager],
      scheduledEvents: [GuildScheduledEventManager],
      available: true,
      shardId: 0,
      splash: null,
      banner: null,
      description: null,
      verificationLevel: 'NONE',
      vanityURLCode: null,
      nsfwLevel: 'DEFAULT',
      premiumSubscriptionCount: 0,
      discoverySplash: null,
      memberCount: 9,
      large: false,
      premiumProgressBarEnabled: false,
      applicationId: null,
      afkTimeout: 300,
      afkChannelId: null,
      systemChannelId: null,
      premiumTier: 'NONE',
      explicitContentFilter: 'DISABLED',
      mfaLevel: 'NONE',
      joinedTimestamp: 1653690625094,
      defaultMessageNotifications: 'ALL_MESSAGES',
      systemChannelFlags: [SystemChannelFlags],
      maximumMembers: 500000,
      maximumPresences: null,
      approximateMemberCount: null,
      approximatePresenceCount: null,
      vanityURLUses: null,
      rulesChannelId: null,
      publicUpdatesChannelId: null,
      preferredLocale: 'en-US',
      ownerId: '342390906097500160',
      emojis: [GuildEmojiManager],
      stickers: [GuildStickerManager]
    },
    guildId: '978660471286665256',
    parentId: '979862662320128041',
    permissionOverwrites: PermissionOverwriteManager { channel: [Circular *6] },
    id: '979862674462621776',
    name: '《🎧》conversar',
    rawPosition: 0,
    rtcRegion: null,
    bitrate: 64000,
    userLimit: 0,
    videoQualityMode: null
  },
  '979862675553140776' => <ref *7> TextChannel {
    type: 'GUILD_TEXT',
    guild: Guild {
      id: '978660471286665256',
      name: 'Hifuzion',
      icon: '7e6391e8eb99e881b2821d011523ee54',
      features: [],
      commands: [GuildApplicationCommandManager],
      members: [GuildMemberManager],
      channels: [GuildChannelManager],
      bans: [GuildBanManager],
      roles: [RoleManager],
      presences: PresenceManager {},
      voiceStates: [VoiceStateManager],
      stageInstances: [StageInstanceManager],
      invites: [GuildInviteManager],
      scheduledEvents: [GuildScheduledEventManager],
      available: true,
      shardId: 0,
      splash: null,
      banner: null,
      description: null,
      verificationLevel: 'NONE',
      vanityURLCode: null,
      nsfwLevel: 'DEFAULT',
      premiumSubscriptionCount: 0,
      discoverySplash: null,
      memberCount: 9,
      large: false,
      premiumProgressBarEnabled: false,
      applicationId: null,
      afkTimeout: 300,
      afkChannelId: null,
      systemChannelId: null,
      premiumTier: 'NONE',
      explicitContentFilter: 'DISABLED',
      mfaLevel: 'NONE',
      joinedTimestamp: 1653690625094,
      defaultMessageNotifications: 'ALL_MESSAGES',
      systemChannelFlags: [SystemChannelFlags],
      maximumMembers: 500000,
      maximumPresences: null,
      approximateMemberCount: null,
      approximatePresenceCount: null,
      vanityURLUses: null,
      rulesChannelId: null,
      publicUpdatesChannelId: null,
      preferredLocale: 'en-US',
      ownerId: '342390906097500160',
      emojis: [GuildEmojiManager],
      stickers: [GuildStickerManager]
    },
    guildId: '978660471286665256',
    parentId: '979862662320128041',
    permissionOverwrites: PermissionOverwriteManager { channel: [Circular *7] },
    messages: MessageManager { channel: [Circular *7] },
    threads: ThreadManager { channel: [Circular *7] },
    nsfw: false,
    id: '979862675553140776',
    name: '《🔊》chat-pessoal',
    rawPosition: 1,
    topic: null,
    lastMessageId: null,
    rateLimitPerUser: 0
  },
  '979862677549621258' => <ref *8> TextChannel {
    type: 'GUILD_TEXT',
    guild: Guild {
      id: '978660471286665256',
      name: 'Hifuzion',
      icon: '7e6391e8eb99e881b2821d011523ee54',
      features: [],
      commands: [GuildApplicationCommandManager],
      members: [GuildMemberManager],
      channels: [GuildChannelManager],
      bans: [GuildBanManager],
      roles: [RoleManager],
      presences: PresenceManager {},
      voiceStates: [VoiceStateManager],
      stageInstances: [StageInstanceManager],
      invites: [GuildInviteManager],
      scheduledEvents: [GuildScheduledEventManager],
      available: true,
      shardId: 0,
      splash: null,
      banner: null,
      description: null,
      verificationLevel: 'NONE',
      vanityURLCode: null,
      nsfwLevel: 'DEFAULT',
      premiumSubscriptionCount: 0,
      discoverySplash: null,
      memberCount: 9,
      large: false,
      premiumProgressBarEnabled: false,
      applicationId: null,
      afkTimeout: 300,
      afkChannelId: null,
      systemChannelId: null,
      premiumTier: 'NONE',
      explicitContentFilter: 'DISABLED',
      mfaLevel: 'NONE',
      joinedTimestamp: 1653690625094,
      defaultMessageNotifications: 'ALL_MESSAGES',
      systemChannelFlags: [SystemChannelFlags],
      maximumMembers: 500000,
      maximumPresences: null,
      approximateMemberCount: null,
      approximatePresenceCount: null,
      vanityURLUses: null,
      rulesChannelId: null,
      publicUpdatesChannelId: null,
      preferredLocale: 'en-US',
      ownerId: '342390906097500160',
      emojis: [GuildEmojiManager],
      stickers: [GuildStickerManager]
    },
    guildId: '978660471286665256',
    parentId: '979862662320128041',
    permissionOverwrites: PermissionOverwriteManager { channel: [Circular *8] },
    messages: MessageManager { channel: [Circular *8] },
    threads: ThreadManager { channel: [Circular *8] },
    nsfw: false,
    id: '979862677549621258',
    name: '《📑》server-register',
    rawPosition: 2,
    topic: null,
    lastMessageId: null,
    rateLimitPerUser: 0
  },
  '979862679348998154' => <ref *9> TextChannel {
    type: 'GUILD_TEXT',
    guild: Guild {
      id: '978660471286665256',
      name: 'Hifuzion',
      icon: '7e6391e8eb99e881b2821d011523ee54',
      features: [],
      commands: [GuildApplicationCommandManager],
      members: [GuildMemberManager],
      channels: [GuildChannelManager],
      bans: [GuildBanManager],
      roles: [RoleManager],
      presences: PresenceManager {},
      voiceStates: [VoiceStateManager],
      stageInstances: [StageInstanceManager],
      invites: [GuildInviteManager],
      scheduledEvents: [GuildScheduledEventManager],
      available: true,
      shardId: 0,
      splash: null,
      banner: null,
      description: null,
      verificationLevel: 'NONE',
      vanityURLCode: null,
      nsfwLevel: 'DEFAULT',
      premiumSubscriptionCount: 0,
      discoverySplash: null,
      memberCount: 9,
      large: false,
      premiumProgressBarEnabled: false,
      applicationId: null,
      afkTimeout: 300,
      afkChannelId: null,
      systemChannelId: null,
      premiumTier: 'NONE',
      explicitContentFilter: 'DISABLED',
      mfaLevel: 'NONE',
      joinedTimestamp: 1653690625094,
      defaultMessageNotifications: 'ALL_MESSAGES',
      systemChannelFlags: [SystemChannelFlags],
      maximumMembers: 500000,
      maximumPresences: null,
      approximateMemberCount: null,
      approximatePresenceCount: null,
      vanityURLUses: null,
      rulesChannelId: null,
      publicUpdatesChannelId: null,
      preferredLocale: 'en-US',
      ownerId: '342390906097500160',
      emojis: [GuildEmojiManager],
      stickers: [GuildStickerManager]
    },
    guildId: '978660471286665256',
    parentId: '979862662320128041',
    permissionOverwrites: PermissionOverwriteManager { channel: [Circular *9] },
    messages: MessageManager { channel: [Circular *9] },
    threads: ThreadManager { channel: [Circular *9] },
    nsfw: false,
    id: '979862679348998154',
    name: '《👁》event-log',
    rawPosition: 3,
    topic: null,
    lastMessageId: null,
    rateLimitPerUser: 0
  },
  '979862681249022023' => <ref *10> TextChannel {
    type: 'GUILD_TEXT',
    guild: Guild {
      id: '978660471286665256',
      name: 'Hifuzion',
      icon: '7e6391e8eb99e881b2821d011523ee54',
      features: [],
      commands: [GuildApplicationCommandManager],
      members: [GuildMemberManager],
      channels: [GuildChannelManager],
      bans: [GuildBanManager],
      roles: [RoleManager],
      presences: PresenceManager {},
      voiceStates: [VoiceStateManager],
      stageInstances: [StageInstanceManager],
      invites: [GuildInviteManager],
      scheduledEvents: [GuildScheduledEventManager],
      available: true,
      shardId: 0,
      splash: null,
      banner: null,
      description: null,
      verificationLevel: 'NONE',
      vanityURLCode: null,
      nsfwLevel: 'DEFAULT',
      premiumSubscriptionCount: 0,
      discoverySplash: null,
      memberCount: 9,
      large: false,
      premiumProgressBarEnabled: false,
      applicationId: null,
      afkTimeout: 300,
      afkChannelId: null,
      systemChannelId: null,
      premiumTier: 'NONE',
      explicitContentFilter: 'DISABLED',
      mfaLevel: 'NONE',
      joinedTimestamp: 1653690625094,
      defaultMessageNotifications: 'ALL_MESSAGES',
      systemChannelFlags: [SystemChannelFlags],
      maximumMembers: 500000,
      maximumPresences: null,
      approximateMemberCount: null,
      approximatePresenceCount: null,
      vanityURLUses: null,
      rulesChannelId: null,
      publicUpdatesChannelId: null,
      preferredLocale: 'en-US',
      ownerId: '342390906097500160',
      emojis: [GuildEmojiManager],
      stickers: [GuildStickerManager]
    },
    guildId: '978660471286665256',
    parentId: '979862663565828106',
    permissionOverwrites: PermissionOverwriteManager { channel: [Circular *10] },
    messages: MessageManager { channel: [Circular *10] },
    threads: ThreadManager { channel: [Circular *10] },
    nsfw: false,
    id: '979862681249022023',
    name: '《📖》rules',
    rawPosition: 7,
    topic: null,
    lastMessageId: null,
    rateLimitPerUser: 0
  },
  '979862685334274058' => <ref *11> TextChannel {
    type: 'GUILD_TEXT',
    guild: Guild {
      id: '978660471286665256',
      name: 'Hifuzion',
      icon: '7e6391e8eb99e881b2821d011523ee54',
      features: [],
      commands: [GuildApplicationCommandManager],
      members: [GuildMemberManager],
      channels: [GuildChannelManager],
      bans: [GuildBanManager],
      roles: [RoleManager],
      presences: PresenceManager {},
      voiceStates: [VoiceStateManager],
      stageInstances: [StageInstanceManager],
      invites: [GuildInviteManager],
      scheduledEvents: [GuildScheduledEventManager],
      available: true,
      shardId: 0,
      splash: null,
      banner: null,
      description: null,
      verificationLevel: 'NONE',
      vanityURLCode: null,
      nsfwLevel: 'DEFAULT',
      premiumSubscriptionCount: 0,
      discoverySplash: null,
      memberCount: 9,
      large: false,
      premiumProgressBarEnabled: false,
      applicationId: null,
      afkTimeout: 300,
      afkChannelId: null,
      systemChannelId: null,
      premiumTier: 'NONE',
      explicitContentFilter: 'DISABLED',
      mfaLevel: 'NONE',
      joinedTimestamp: 1653690625094,
      defaultMessageNotifications: 'ALL_MESSAGES',
      systemChannelFlags: [SystemChannelFlags],
      maximumMembers: 500000,
      maximumPresences: null,
      approximateMemberCount: null,
      approximatePresenceCount: null,
      vanityURLUses: null,
      rulesChannelId: null,
      publicUpdatesChannelId: null,
      preferredLocale: 'en-US',
      ownerId: '342390906097500160',
      emojis: [GuildEmojiManager],
      stickers: [GuildStickerManager]
    },
    guildId: '978660471286665256',
    parentId: '979862663565828106',
    permissionOverwrites: PermissionOverwriteManager { channel: [Circular *11] },
    messages: MessageManager { channel: [Circular *11] },
    threads: ThreadManager { channel: [Circular *11] },
    nsfw: false,
    id: '979862685334274058',
    name: '《🧮》verificação',
    rawPosition: 8,
    topic: null,
    lastMessageId: '979881483005206568',
    rateLimitPerUser: 0
  },
  '979862692959514624' => <ref *12> TextChannel {
    type: 'GUILD_TEXT',
    guild: Guild {
      id: '978660471286665256',
      name: 'Hifuzion',
      icon: '7e6391e8eb99e881b2821d011523ee54',
      features: [],
      commands: [GuildApplicationCommandManager],
      members: [GuildMemberManager],
      channels: [GuildChannelManager],
      bans: [GuildBanManager],
      roles: [RoleManager],
      presences: PresenceManager {},
      voiceStates: [VoiceStateManager],
      stageInstances: [StageInstanceManager],
      invites: [GuildInviteManager],
      scheduledEvents: [GuildScheduledEventManager],
      available: true,
      shardId: 0,
      splash: null,
      banner: null,
      description: null,
      verificationLevel: 'NONE',
      vanityURLCode: null,
      nsfwLevel: 'DEFAULT',
      premiumSubscriptionCount: 0,
      discoverySplash: null,
      memberCount: 9,
      large: false,
      premiumProgressBarEnabled: false,
      applicationId: null,
      afkTimeout: 300,
      afkChannelId: null,
      systemChannelId: null,
      premiumTier: 'NONE',
      explicitContentFilter: 'DISABLED',
      mfaLevel: 'NONE',
      joinedTimestamp: 1653690625094,
      defaultMessageNotifications: 'ALL_MESSAGES',
      systemChannelFlags: [SystemChannelFlags],
      maximumMembers: 500000,
      maximumPresences: null,
      approximateMemberCount: null,
      approximatePresenceCount: null,
      vanityURLUses: null,
      rulesChannelId: null,
      publicUpdatesChannelId: null,
      preferredLocale: 'en-US',
      ownerId: '342390906097500160',
      emojis: [GuildEmojiManager],
      stickers: [GuildStickerManager]
    },
    guildId: '978660471286665256',
    parentId: '979862664585027584',
    permissionOverwrites: PermissionOverwriteManager { channel: [Circular *12] },
    messages: MessageManager { channel: [Circular *12] },
    threads: ThreadManager { channel: [Circular *12] },
    nsfw: false,
    id: '979862692959514624',
    name: '《🗞》chat',
    rawPosition: 10,
    topic: null,
    lastMessageId: null,
    rateLimitPerUser: 0
  },
  '979862696839233576' => <ref *13> TextChannel {
    type: 'GUILD_TEXT',
    guild: Guild {
      id: '978660471286665256',
      name: 'Hifuzion',
      icon: '7e6391e8eb99e881b2821d011523ee54',
      features: [],
      commands: [GuildApplicationCommandManager],
      members: [GuildMemberManager],
      channels: [GuildChannelManager],
      bans: [GuildBanManager],
      roles: [RoleManager],
      presences: PresenceManager {},
      voiceStates: [VoiceStateManager],
      stageInstances: [StageInstanceManager],
      invites: [GuildInviteManager],
      scheduledEvents: [GuildScheduledEventManager],
      available: true,
      shardId: 0,
      splash: null,
      banner: null,
      description: null,
      verificationLevel: 'NONE',
      vanityURLCode: null,
      nsfwLevel: 'DEFAULT',
      premiumSubscriptionCount: 0,
      discoverySplash: null,
      memberCount: 9,
      large: false,
      premiumProgressBarEnabled: false,
      applicationId: null,
      afkTimeout: 300,
      afkChannelId: null,
      systemChannelId: null,
      premiumTier: 'NONE',
      explicitContentFilter: 'DISABLED',
      mfaLevel: 'NONE',
      joinedTimestamp: 1653690625094,
      defaultMessageNotifications: 'ALL_MESSAGES',
      systemChannelFlags: [SystemChannelFlags],
      maximumMembers: 500000,
      maximumPresences: null,
      approximateMemberCount: null,
      approximatePresenceCount: null,
      vanityURLUses: null,
      rulesChannelId: null,
      publicUpdatesChannelId: null,
      preferredLocale: 'en-US',
      ownerId: '342390906097500160',
      emojis: [GuildEmojiManager],
      stickers: [GuildStickerManager]
    },
    guildId: '978660471286665256',
    parentId: '979862664585027584',
    permissionOverwrites: PermissionOverwriteManager { channel: [Circular *13] },
    messages: MessageManager { channel: [Circular *13] },
    threads: ThreadManager { channel: [Circular *13] },
    nsfw: false,
    id: '979862696839233576',
    name: '《💻》commands',
    rawPosition: 11,
    topic: null,
    lastMessageId: null,
    rateLimitPerUser: 0
  },
  '979862698927992882' => <ref *14> TextChannel {
    type: 'GUILD_TEXT',
    guild: Guild {
      id: '978660471286665256',
      name: 'Hifuzion',
      icon: '7e6391e8eb99e881b2821d011523ee54',
      features: [],
      commands: [GuildApplicationCommandManager],
      members: [GuildMemberManager],
      channels: [GuildChannelManager],
      bans: [GuildBanManager],
      roles: [RoleManager],
      presences: PresenceManager {},
      voiceStates: [VoiceStateManager],
      stageInstances: [StageInstanceManager],
      invites: [GuildInviteManager],
      scheduledEvents: [GuildScheduledEventManager],
      available: true,
      shardId: 0,
      splash: null,
      banner: null,
      description: null,
      verificationLevel: 'NONE',
      vanityURLCode: null,
      nsfwLevel: 'DEFAULT',
      premiumSubscriptionCount: 0,
      discoverySplash: null,
      memberCount: 9,
      large: false,
      premiumProgressBarEnabled: false,
      applicationId: null,
      afkTimeout: 300,
      afkChannelId: null,
      systemChannelId: null,
      premiumTier: 'NONE',
      explicitContentFilter: 'DISABLED',
      mfaLevel: 'NONE',
      joinedTimestamp: 1653690625094,
      defaultMessageNotifications: 'ALL_MESSAGES',
      systemChannelFlags: [SystemChannelFlags],
      maximumMembers: 500000,
      maximumPresences: null,
      approximateMemberCount: null,
      approximatePresenceCount: null,
      vanityURLUses: null,
      rulesChannelId: null,
      publicUpdatesChannelId: null,
      preferredLocale: 'en-US',
      ownerId: '342390906097500160',
      emojis: [GuildEmojiManager],
      stickers: [GuildStickerManager]
    },
    guildId: '978660471286665256',
    parentId: '979862662320128041',
    permissionOverwrites: PermissionOverwriteManager { channel: [Circular *14] },
    messages: MessageManager { channel: [Circular *14] },
    threads: ThreadManager { channel: [Circular *14] },
    nsfw: false,
    id: '979862698927992882',
    name: '《🤝》staff',
    rawPosition: 6,
    topic: null,
    lastMessageId: null,
    rateLimitPerUser: 0
  },
  '979862705416593489' => <ref *15> TextChannel {
    type: 'GUILD_TEXT',
    guild: Guild {
      id: '978660471286665256',
      name: 'Hifuzion',
      icon: '7e6391e8eb99e881b2821d011523ee54',
      features: [],
      commands: [GuildApplicationCommandManager],
      members: [GuildMemberManager],
      channels: [GuildChannelManager],
      bans: [GuildBanManager],
      roles: [RoleManager],
      presences: PresenceManager {},
      voiceStates: [VoiceStateManager],
      stageInstances: [StageInstanceManager],
      invites: [GuildInviteManager],
      scheduledEvents: [GuildScheduledEventManager],
      available: true,
      shardId: 0,
      splash: null,
      banner: null,
      description: null,
      verificationLevel: 'NONE',
      vanityURLCode: null,
      nsfwLevel: 'DEFAULT',
      premiumSubscriptionCount: 0,
      discoverySplash: null,
      memberCount: 9,
      large: false,
      premiumProgressBarEnabled: false,
      applicationId: null,
      afkTimeout: 300,
      afkChannelId: null,
      systemChannelId: null,
      premiumTier: 'NONE',
      explicitContentFilter: 'DISABLED',
      mfaLevel: 'NONE',
      joinedTimestamp: 1653690625094,
      defaultMessageNotifications: 'ALL_MESSAGES',
      systemChannelFlags: [SystemChannelFlags],
      maximumMembers: 500000,
      maximumPresences: null,
      approximateMemberCount: null,
      approximatePresenceCount: null,
      vanityURLUses: null,
      rulesChannelId: null,
      publicUpdatesChannelId: null,
      preferredLocale: 'en-US',
      ownerId: '342390906097500160',
      emojis: [GuildEmojiManager],
      stickers: [GuildStickerManager]
    },
    guildId: '978660471286665256',
    parentId: '979862668301201418',
    permissionOverwrites: PermissionOverwriteManager { channel: [Circular *15] },
    messages: MessageManager { channel: [Circular *15] },
    threads: ThreadManager { channel: [Circular *15] },
    nsfw: false,
    id: '979862705416593489',
    name: '《👻》memes',
    rawPosition: 13,
    topic: null,
    lastMessageId: '982270818073600060',
    rateLimitPerUser: 0
  },
  '979862720365096970' => <ref *16> TextChannel {
    type: 'GUILD_TEXT',
    guild: Guild {
      id: '978660471286665256',
      name: 'Hifuzion',
      icon: '7e6391e8eb99e881b2821d011523ee54',
      features: [],
      commands: [GuildApplicationCommandManager],
      members: [GuildMemberManager],
      channels: [GuildChannelManager],
      bans: [GuildBanManager],
      roles: [RoleManager],
      presences: PresenceManager {},
      voiceStates: [VoiceStateManager],
      stageInstances: [StageInstanceManager],
      invites: [GuildInviteManager],
      scheduledEvents: [GuildScheduledEventManager],
      available: true,
      shardId: 0,
      splash: null,
      banner: null,
      description: null,
      verificationLevel: 'NONE',
      vanityURLCode: null,
      nsfwLevel: 'DEFAULT',
      premiumSubscriptionCount: 0,
      discoverySplash: null,
      memberCount: 9,
      large: false,
      premiumProgressBarEnabled: false,
      applicationId: null,
      afkTimeout: 300,
      afkChannelId: null,
      systemChannelId: null,
      premiumTier: 'NONE',
      explicitContentFilter: 'DISABLED',
      mfaLevel: 'NONE',
      joinedTimestamp: 1653690625094,
      defaultMessageNotifications: 'ALL_MESSAGES',
      systemChannelFlags: [SystemChannelFlags],
      maximumMembers: 500000,
      maximumPresences: null,
      approximateMemberCount: null,
      approximatePresenceCount: null,
      vanityURLUses: null,
      rulesChannelId: null,
      publicUpdatesChannelId: null,
      preferredLocale: 'en-US',
      ownerId: '342390906097500160',
      emojis: [GuildEmojiManager],
      stickers: [GuildStickerManager]
    },
    guildId: '978660471286665256',
    parentId: '979862668301201418',
    permissionOverwrites: PermissionOverwriteManager { channel: [Circular *16] },
    messages: MessageManager { channel: [Circular *16] },
    threads: ThreadManager { channel: [Circular *16] },
    nsfw: false,
    id: '979862720365096970',
    name: '《💻》programação',
    rawPosition: 14,
    topic: null,
    lastMessageId: null,
    rateLimitPerUser: 0
  },
  '979862722248319077' => <ref *17> TextChannel {
    type: 'GUILD_TEXT',
    guild: Guild {
      id: '978660471286665256',
      name: 'Hifuzion',
      icon: '7e6391e8eb99e881b2821d011523ee54',
      features: [],
      commands: [GuildApplicationCommandManager],
      members: [GuildMemberManager],
      channels: [GuildChannelManager],
      bans: [GuildBanManager],
      roles: [RoleManager],
      presences: PresenceManager {},
      voiceStates: [VoiceStateManager],
      stageInstances: [StageInstanceManager],
      invites: [GuildInviteManager],
      scheduledEvents: [GuildScheduledEventManager],
      available: true,
      shardId: 0,
      splash: null,
      banner: null,
      description: null,
      verificationLevel: 'NONE',
      vanityURLCode: null,
      nsfwLevel: 'DEFAULT',
      premiumSubscriptionCount: 0,
      discoverySplash: null,
      memberCount: 9,
      large: false,
      premiumProgressBarEnabled: false,
      applicationId: null,
      afkTimeout: 300,
      afkChannelId: null,
      systemChannelId: null,
      premiumTier: 'NONE',
      explicitContentFilter: 'DISABLED',
      mfaLevel: 'NONE',
      joinedTimestamp: 1653690625094,
      defaultMessageNotifications: 'ALL_MESSAGES',
      systemChannelFlags: [SystemChannelFlags],
      maximumMembers: 500000,
      maximumPresences: null,
      approximateMemberCount: null,
      approximatePresenceCount: null,
      vanityURLUses: null,
      rulesChannelId: null,
      publicUpdatesChannelId: null,
      preferredLocale: 'en-US',
      ownerId: '342390906097500160',
      emojis: [GuildEmojiManager],
      stickers: [GuildStickerManager]
    },
    guildId: '978660471286665256',
    parentId: '979862664585027584',
    permissionOverwrites: PermissionOverwriteManager { channel: [Circular *17] },
    messages: MessageManager { channel: [Circular *17] },
    threads: ThreadManager { channel: [Circular *17] },
    nsfw: false,
    id: '979862722248319077',
    name: '《☕》ideias',
    rawPosition: 12,
    topic: null,
    lastMessageId: null,
    rateLimitPerUser: 0
  },
  '979862723460464681' => <ref *18> TextChannel {
    type: 'GUILD_TEXT',
    guild: Guild {
      id: '978660471286665256',
      name: 'Hifuzion',
      icon: '7e6391e8eb99e881b2821d011523ee54',
      features: [],
      commands: [GuildApplicationCommandManager],
      members: [GuildMemberManager],
      channels: [GuildChannelManager],
      bans: [GuildBanManager],
      roles: [RoleManager],
      presences: PresenceManager {},
      voiceStates: [VoiceStateManager],
      stageInstances: [StageInstanceManager],
      invites: [GuildInviteManager],
      scheduledEvents: [GuildScheduledEventManager],
      available: true,
      shardId: 0,
      splash: null,
      banner: null,
      description: null,
      verificationLevel: 'NONE',
      vanityURLCode: null,
      nsfwLevel: 'DEFAULT',
      premiumSubscriptionCount: 0,
      discoverySplash: null,
      memberCount: 9,
      large: false,
      premiumProgressBarEnabled: false,
      applicationId: null,
      afkTimeout: 300,
      afkChannelId: null,
      systemChannelId: null,
      premiumTier: 'NONE',
      explicitContentFilter: 'DISABLED',
      mfaLevel: 'NONE',
      joinedTimestamp: 1653690625094,
      defaultMessageNotifications: 'ALL_MESSAGES',
      systemChannelFlags: [SystemChannelFlags],
      maximumMembers: 500000,
      maximumPresences: null,
      approximateMemberCount: null,
      approximatePresenceCount: null,
      vanityURLUses: null,
      rulesChannelId: null,
      publicUpdatesChannelId: null,
      preferredLocale: 'en-US',
      ownerId: '342390906097500160',
      emojis: [GuildEmojiManager],
      stickers: [GuildStickerManager]
    },
    guildId: '978660471286665256',
    parentId: '979862662320128041',
    permissionOverwrites: PermissionOverwriteManager { channel: [Circular *18] },
    messages: MessageManager { channel: [Circular *18] },
    threads: ThreadManager { channel: [Circular *18] },
    nsfw: false,
    id: '979862723460464681',
    name: '《🤖》bots-crecendo',
    rawPosition: 5,
    topic: null,
    lastMessageId: null,
    rateLimitPerUser: 0
  },
  '979882178383056946' => <ref *19> TextChannel {
    type: 'GUILD_TEXT',
    guild: Guild {
      id: '978660471286665256',
      name: 'Hifuzion',
      icon: '7e6391e8eb99e881b2821d011523ee54',
      features: [],
      commands: [GuildApplicationCommandManager],
      members: [GuildMemberManager],
      channels: [GuildChannelManager],
      bans: [GuildBanManager],
      roles: [RoleManager],
      presences: PresenceManager {},
      voiceStates: [VoiceStateManager],
      stageInstances: [StageInstanceManager],
      invites: [GuildInviteManager],
      scheduledEvents: [GuildScheduledEventManager],
      available: true,
      shardId: 0,
      splash: null,
      banner: null,
      description: null,
      verificationLevel: 'NONE',
      vanityURLCode: null,
      nsfwLevel: 'DEFAULT',
      premiumSubscriptionCount: 0,
      discoverySplash: null,
      memberCount: 9,
      large: false,
      premiumProgressBarEnabled: false,
      applicationId: null,
      afkTimeout: 300,
      afkChannelId: null,
      systemChannelId: null,
      premiumTier: 'NONE',
      explicitContentFilter: 'DISABLED',
      mfaLevel: 'NONE',
      joinedTimestamp: 1653690625094,
      defaultMessageNotifications: 'ALL_MESSAGES',
      systemChannelFlags: [SystemChannelFlags],
      maximumMembers: 500000,
      maximumPresences: null,
      approximateMemberCount: null,
      approximatePresenceCount: null,
      vanityURLUses: null,
      rulesChannelId: null,
      publicUpdatesChannelId: null,
      preferredLocale: 'en-US',
      ownerId: '342390906097500160',
      emojis: [GuildEmojiManager],
      stickers: [GuildStickerManager]
    },
    guildId: '978660471286665256',
    parentId: '979862668301201418',
    permissionOverwrites: PermissionOverwriteManager { channel: [Circular *19] },
    messages: MessageManager { channel: [Circular *19] },
    threads: ThreadManager { channel: [Circular *19] },
    nsfw: false,
    id: '979882178383056946',
    name: '《💻》projetos',
    rawPosition: 15,
    topic: null,
    lastMessageId: null,
    rateLimitPerUser: 0
  },
  '979882288462590042' => <ref *20> VoiceChannel {
    type: 'GUILD_VOICE',
    guild: Guild {
      id: '978660471286665256',
      name: 'Hifuzion',
      icon: '7e6391e8eb99e881b2821d011523ee54',
      features: [],
      commands: [GuildApplicationCommandManager],
      members: [GuildMemberManager],
      channels: [GuildChannelManager],
      bans: [GuildBanManager],
      roles: [RoleManager],
      presences: PresenceManager {},
      voiceStates: [VoiceStateManager],
      stageInstances: [StageInstanceManager],
      invites: [GuildInviteManager],
      scheduledEvents: [GuildScheduledEventManager],
      available: true,
      shardId: 0,
      splash: null,
      banner: null,
      description: null,
      verificationLevel: 'NONE',
      vanityURLCode: null,
      nsfwLevel: 'DEFAULT',
      premiumSubscriptionCount: 0,
      discoverySplash: null,
      memberCount: 9,
      large: false,
      premiumProgressBarEnabled: false,
      applicationId: null,
      afkTimeout: 300,
      afkChannelId: null,
      systemChannelId: null,
      premiumTier: 'NONE',
      explicitContentFilter: 'DISABLED',
      mfaLevel: 'NONE',
      joinedTimestamp: 1653690625094,
      defaultMessageNotifications: 'ALL_MESSAGES',
      systemChannelFlags: [SystemChannelFlags],
      maximumMembers: 500000,
      maximumPresences: null,
      approximateMemberCount: null,
      approximatePresenceCount: null,
      vanityURLUses: null,
      rulesChannelId: null,
      publicUpdatesChannelId: null,
      preferredLocale: 'en-US',
      ownerId: '342390906097500160',
      emojis: [GuildEmojiManager],
      stickers: [GuildStickerManager]
    },
    guildId: '978660471286665256',
    parentId: '979862668301201418',
    permissionOverwrites: PermissionOverwriteManager { channel: [Circular *20] },
    id: '979882288462590042',
    name: '《💻》cantinho dos programadores',
    rawPosition: 7,
    rtcRegion: null,
    bitrate: 64000,
    userLimit: 0,
    videoQualityMode: null
  },
  '979882589101887559' => <ref *21> CategoryChannel {
    type: 'GUILD_CATEGORY',
    guild: Guild {
      id: '978660471286665256',
      name: 'Hifuzion',
      icon: '7e6391e8eb99e881b2821d011523ee54',
      features: [],
      commands: [GuildApplicationCommandManager],
      members: [GuildMemberManager],
      channels: [GuildChannelManager],
      bans: [GuildBanManager],
      roles: [RoleManager],
      presences: PresenceManager {},
      voiceStates: [VoiceStateManager],
      stageInstances: [StageInstanceManager],
      invites: [GuildInviteManager],
      scheduledEvents: [GuildScheduledEventManager],
      available: true,
      shardId: 0,
      splash: null,
      banner: null,
      description: null,
      verificationLevel: 'NONE',
      vanityURLCode: null,
      nsfwLevel: 'DEFAULT',
      premiumSubscriptionCount: 0,
      discoverySplash: null,
      memberCount: 9,
      large: false,
      premiumProgressBarEnabled: false,
      applicationId: null,
      afkTimeout: 300,
      afkChannelId: null,
      systemChannelId: null,
      premiumTier: 'NONE',
      explicitContentFilter: 'DISABLED',
      mfaLevel: 'NONE',
      joinedTimestamp: 1653690625094,
      defaultMessageNotifications: 'ALL_MESSAGES',
      systemChannelFlags: [SystemChannelFlags],
      maximumMembers: 500000,
      maximumPresences: null,
      approximateMemberCount: null,
      approximatePresenceCount: null,
      vanityURLUses: null,
      rulesChannelId: null,
      publicUpdatesChannelId: null,
      preferredLocale: 'en-US',
      ownerId: '342390906097500160',
      emojis: [GuildEmojiManager],
      stickers: [GuildStickerManager]
    },
    guildId: '978660471286665256',
    parentId: null,
    permissionOverwrites: PermissionOverwriteManager { channel: [Circular *21] },
    id: '979882589101887559',
    name: '《🗞》Suporte',
    rawPosition: 2
  },
  '979882846321791046' => <ref *22> TextChannel {
    type: 'GUILD_TEXT',
    guild: Guild {
      id: '978660471286665256',
      name: 'Hifuzion',
      icon: '7e6391e8eb99e881b2821d011523ee54',
      features: [],
      commands: [GuildApplicationCommandManager],
      members: [GuildMemberManager],
      channels: [GuildChannelManager],
      bans: [GuildBanManager],
      roles: [RoleManager],
      presences: PresenceManager {},
      voiceStates: [VoiceStateManager],
      stageInstances: [StageInstanceManager],
      invites: [GuildInviteManager],
      scheduledEvents: [GuildScheduledEventManager],
      available: true,
      shardId: 0,
      splash: null,
      banner: null,
      description: null,
      verificationLevel: 'NONE',
      vanityURLCode: null,
      nsfwLevel: 'DEFAULT',
      premiumSubscriptionCount: 0,
      discoverySplash: null,
      memberCount: 9,
      large: false,
      premiumProgressBarEnabled: false,
      applicationId: null,
      afkTimeout: 300,
      afkChannelId: null,
      systemChannelId: null,
      premiumTier: 'NONE',
      explicitContentFilter: 'DISABLED',
      mfaLevel: 'NONE',
      joinedTimestamp: 1653690625094,
      defaultMessageNotifications: 'ALL_MESSAGES',
      systemChannelFlags: [SystemChannelFlags],
      maximumMembers: 500000,
      maximumPresences: null,
      approximateMemberCount: null,
      approximatePresenceCount: null,
      vanityURLUses: null,
      rulesChannelId: null,
      publicUpdatesChannelId: null,
      preferredLocale: 'en-US',
      ownerId: '342390906097500160',
      emojis: [GuildEmojiManager],
      stickers: [GuildStickerManager]
    },
    guildId: '978660471286665256',
    parentId: '979882589101887559',
    permissionOverwrites: PermissionOverwriteManager { channel: [Circular *22] },
    messages: MessageManager { channel: [Circular *22] },
    threads: ThreadManager { channel: [Circular *22] },
    nsfw: false,
    id: '979882846321791046',
    name: '《📑》suporte',
    rawPosition: 9,
    topic: null,
    lastMessageId: '982331348427616256',
    rateLimitPerUser: 0
  },
  '979883491477057556' => <ref *23> VoiceChannel {
    type: 'GUILD_VOICE',
    guild: Guild {
      id: '978660471286665256',
      name: 'Hifuzion',
      icon: '7e6391e8eb99e881b2821d011523ee54',
      features: [],
      commands: [GuildApplicationCommandManager],
      members: [GuildMemberManager],
      channels: [GuildChannelManager],
      bans: [GuildBanManager],
      roles: [RoleManager],
      presences: PresenceManager {},
      voiceStates: [VoiceStateManager],
      stageInstances: [StageInstanceManager],
      invites: [GuildInviteManager],
      scheduledEvents: [GuildScheduledEventManager],
      available: true,
      shardId: 0,
      splash: null,
      banner: null,
      description: null,
      verificationLevel: 'NONE',
      vanityURLCode: null,
      nsfwLevel: 'DEFAULT',
      premiumSubscriptionCount: 0,
      discoverySplash: null,
      memberCount: 9,
      large: false,
      premiumProgressBarEnabled: false,
      applicationId: null,
      afkTimeout: 300,
      afkChannelId: null,
      systemChannelId: null,
      premiumTier: 'NONE',
      explicitContentFilter: 'DISABLED',
      mfaLevel: 'NONE',
      joinedTimestamp: 1653690625094,
      defaultMessageNotifications: 'ALL_MESSAGES',
      systemChannelFlags: [SystemChannelFlags],
      maximumMembers: 500000,
      maximumPresences: null,
      approximateMemberCount: null,
      approximatePresenceCount: null,
      vanityURLUses: null,
      rulesChannelId: null,
      publicUpdatesChannelId: null,
      preferredLocale: 'en-US',
      ownerId: '342390906097500160',
      emojis: [GuildEmojiManager],
      stickers: [GuildStickerManager]
    },
    guildId: '978660471286665256',
    parentId: '979882589101887559',
    permissionOverwrites: PermissionOverwriteManager { channel: [Circular *23] },
    id: '979883491477057556',
    name: '《🔊》Suporte ¹',
    rawPosition: 0,
    rtcRegion: null,
    bitrate: 64000,
    userLimit: 2,
    videoQualityMode: null
  },
  '979883633911422976' => <ref *24> VoiceChannel {
    type: 'GUILD_VOICE',
    guild: Guild {
      id: '978660471286665256',
      name: 'Hifuzion',
      icon: '7e6391e8eb99e881b2821d011523ee54',
      features: [],
      commands: [GuildApplicationCommandManager],
      members: [GuildMemberManager],
      channels: [GuildChannelManager],
      bans: [GuildBanManager],
      roles: [RoleManager],
      presences: PresenceManager {},
      voiceStates: [VoiceStateManager],
      stageInstances: [StageInstanceManager],
      invites: [GuildInviteManager],
      scheduledEvents: [GuildScheduledEventManager],
      available: true,
      shardId: 0,
      splash: null,
      banner: null,
      description: null,
      verificationLevel: 'NONE',
      vanityURLCode: null,
      nsfwLevel: 'DEFAULT',
      premiumSubscriptionCount: 0,
      discoverySplash: null,
      memberCount: 9,
      large: false,
      premiumProgressBarEnabled: false,
      applicationId: null,
      afkTimeout: 300,
      afkChannelId: null,
      systemChannelId: null,
      premiumTier: 'NONE',
      explicitContentFilter: 'DISABLED',
      mfaLevel: 'NONE',
      joinedTimestamp: 1653690625094,
      defaultMessageNotifications: 'ALL_MESSAGES',
      systemChannelFlags: [SystemChannelFlags],
      maximumMembers: 500000,
      maximumPresences: null,
      approximateMemberCount: null,
      approximatePresenceCount: null,
      vanityURLUses: null,
      rulesChannelId: null,
      publicUpdatesChannelId: null,
      preferredLocale: 'en-US',
      ownerId: '342390906097500160',
      emojis: [GuildEmojiManager],
      stickers: [GuildStickerManager]
    },
    guildId: '978660471286665256',
    parentId: '979882589101887559',
    permissionOverwrites: PermissionOverwriteManager { channel: [Circular *24] },
    id: '979883633911422976',
    name: '《🔊》Suporte ³',
    rawPosition: 2,
    rtcRegion: null,
    bitrate: 64000,
    userLimit: 2,
    videoQualityMode: null
  },
  '979883872856702976' => <ref *25> VoiceChannel {
    type: 'GUILD_VOICE',
    guild: Guild {
      id: '978660471286665256',
      name: 'Hifuzion',
      icon: '7e6391e8eb99e881b2821d011523ee54',
      features: [],
      commands: [GuildApplicationCommandManager],
      members: [GuildMemberManager],
      channels: [GuildChannelManager],
      bans: [GuildBanManager],
      roles: [RoleManager],
      presences: PresenceManager {},
      voiceStates: [VoiceStateManager],
      stageInstances: [StageInstanceManager],
      invites: [GuildInviteManager],
      scheduledEvents: [GuildScheduledEventManager],
      available: true,
      shardId: 0,
      splash: null,
      banner: null,
      description: null,
      verificationLevel: 'NONE',
      vanityURLCode: null,
      nsfwLevel: 'DEFAULT',
      premiumSubscriptionCount: 0,
      discoverySplash: null,
      memberCount: 9,
      large: false,
      premiumProgressBarEnabled: false,
      applicationId: null,
      afkTimeout: 300,
      afkChannelId: null,
      systemChannelId: null,
      premiumTier: 'NONE',
      explicitContentFilter: 'DISABLED',
      mfaLevel: 'NONE',
      joinedTimestamp: 1653690625094,
      defaultMessageNotifications: 'ALL_MESSAGES',
      systemChannelFlags: [SystemChannelFlags],
      maximumMembers: 500000,
      maximumPresences: null,
      approximateMemberCount: null,
      approximatePresenceCount: null,
      vanityURLUses: null,
      rulesChannelId: null,
      publicUpdatesChannelId: null,
      preferredLocale: 'en-US',
      ownerId: '342390906097500160',
      emojis: [GuildEmojiManager],
      stickers: [GuildStickerManager]
    },
    guildId: '978660471286665256',
    parentId: '979882589101887559',
    permissionOverwrites: PermissionOverwriteManager { channel: [Circular *25] },
    id: '979883872856702976',
    name: '《🔊》Suporte ²',
    rawPosition: 1,
    rtcRegion: null,
    bitrate: 64000,
    userLimit: 2,
    videoQualityMode: null
  },
  '979935171426000896' => <ref *26> TextChannel {
    type: 'GUILD_TEXT',
    guild: Guild {
      id: '978660471286665256',
      name: 'Hifuzion',
      icon: '7e6391e8eb99e881b2821d011523ee54',
      features: [],
      commands: [GuildApplicationCommandManager],
      members: [GuildMemberManager],
      channels: [GuildChannelManager],
      bans: [GuildBanManager],
      roles: [RoleManager],
      presences: PresenceManager {},
      voiceStates: [VoiceStateManager],
      stageInstances: [StageInstanceManager],
      invites: [GuildInviteManager],
      scheduledEvents: [GuildScheduledEventManager],
      available: true,
      shardId: 0,
      splash: null,
      banner: null,
      description: null,
      verificationLevel: 'NONE',
      vanityURLCode: null,
      nsfwLevel: 'DEFAULT',
      premiumSubscriptionCount: 0,
      discoverySplash: null,
      memberCount: 9,
      large: false,
      premiumProgressBarEnabled: false,
      applicationId: null,
      afkTimeout: 300,
      afkChannelId: null,
      systemChannelId: null,
      premiumTier: 'NONE',
      explicitContentFilter: 'DISABLED',
      mfaLevel: 'NONE',
      joinedTimestamp: 1653690625094,
      defaultMessageNotifications: 'ALL_MESSAGES',
      systemChannelFlags: [SystemChannelFlags],
      maximumMembers: 500000,
      maximumPresences: null,
      approximateMemberCount: null,
      approximatePresenceCount: null,
      vanityURLUses: null,
      rulesChannelId: null,
      publicUpdatesChannelId: null,
      preferredLocale: 'en-US',
      ownerId: '342390906097500160',
      emojis: [GuildEmojiManager],
      stickers: [GuildStickerManager]
    },
    guildId: '978660471286665256',
    parentId: '979862662320128041',
    permissionOverwrites: PermissionOverwriteManager { channel: [Circular *26] },
    messages: MessageManager { channel: [Circular *26] },
    threads: ThreadManager { channel: [Circular *26] },
    nsfw: false,
    id: '979935171426000896',
    name: '《👁》ticket-log',
    rawPosition: 4,
    topic: null,
    lastMessageId: '981660229949345793',
    rateLimitPerUser: 0
  },
  maxSize: Infinity,
  keepOverLimit: null,
  sweepFilter: [Function (anonymous)] { isDefault: true },
  interval: Timeout {
    _idleTimeout: 3600000,
    _idlePrev: [Timeout],
    _idleNext: [TimersList],
    _idleStart: 899,
    _onTimeout: [Function (anonymous)],
    _timerArgs: undefined,
    _repeat: 3600000,
    _destroyed: false,
    [Symbol(refed)]: false,
    [Symbol(kHasPrimitive)]: false,
    [Symbol(asyncId)]: 10,
    [Symbol(triggerId)]: 1
  }
}
